version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abhi
      MYSQL_DATABASE: employeedb
    ports:
      - "3306:3306"

  app:
    build: employee
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://employee-db.cgn4wa8mi408.us-east-1.rds.amazonaws.com:3306/employeedb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Abhi.dev1234
