apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/employeedb"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "password"
